---
- required: true
  module: "cas-server-support-saml-idp-metadata-redis"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.RedisSamlMetadataProperties"
  type: "java.lang.Integer"
  description: "Database index used by the connection factory."
  shortDescription: "Database index used by the connection factory."
  name: "cas.authn.saml-idp.metadata.redis.database"
  defaultValue: 0
- required: true
  module: "cas-server-support-saml-idp-metadata-redis"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.RedisSamlMetadataProperties"
  type: "java.lang.Boolean"
  description: "Whether the module is enabled or not, defaults to true."
  shortDescription: "Whether the module is enabled or not, defaults to true."
  name: "cas.authn.saml-idp.metadata.redis.enabled"
  defaultValue: true
- required: true
  module: "cas-server-support-saml-idp-metadata-redis"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.RedisSamlMetadataProperties"
  type: "java.lang.String"
  description: "Redis server host."
  shortDescription: "Redis server host."
  name: "cas.authn.saml-idp.metadata.redis.host"
  defaultValue: "localhost"
- module: "cas-server-support-saml-idp-metadata-redis"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.RedisSamlMetadataProperties"
  type: "java.lang.Boolean"
  description: "Whether identity provider metadata artifacts are expected to be found\
    \ in the database."
  shortDescription: "Whether identity provider metadata artifacts are expected to\
    \ be found in the database."
  name: "cas.authn.saml-idp.metadata.redis.idp-metadata-enabled"
  defaultValue: false
- required: true
  module: "cas-server-support-saml-idp-metadata-redis"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.RedisSamlMetadataProperties"
  type: "java.lang.String"
  description: "Login password of the redis server."
  shortDescription: "Login password of the redis server."
  name: "cas.authn.saml-idp.metadata.redis.password"
  defaultValue: ""
- required: true
  module: "cas-server-support-saml-idp-metadata-redis"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.RedisSamlMetadataProperties"
  type: "java.lang.Integer"
  description: "Redis server port."
  shortDescription: "Redis server port."
  name: "cas.authn.saml-idp.metadata.redis.port"
  defaultValue: 6379
- module: "cas-server-support-saml-idp-metadata-redis"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.RedisSamlMetadataProperties"
  type: "org.apereo.cas.configuration.model.support.redis.BaseRedisProperties$RedisReadFromTypes"
  description: "Setting that describes how Lettuce routes read operations to replica\
    \ nodes. Note that modes referencing MASTER/SLAVE are deprecated (but still supported)\
    \ in the Lettuce redis client dependency so migrate config to UPSTREAM/REPLICA.\n\
    Available values are as follows:\n<ul><li>{@code UPSTREAM}: Read from the current\
    \ upstream node.</li><li>{@code UPSTREAMPREFERRED}: Read from the upstream node,\
    \ but if it is unavailable, read from replica nodes.</li><li>{@code MASTER}: Read\
    \ from the current upstream node.</li><li>{@code MASTERPREFERRED}: Read from the\
    \ upstream node, but if it is unavailable, read from replica nodes.</li><li>{@code\
    \ SLAVE}: Read from replica nodes.</li><li>{@code SLAVEPREFERRED}:  Read from\
    \ the replica nodes, but if none is unavailable, read from the upstream node.</li><li>{@code\
    \ REPLICA}: Read from replica nodes.</li><li>{@code REPLICAPREFERRED}: Read from\
    \ the replica nodes, but if none is unavailable, read from the upstream node.</li><li>{@code\
    \ ANY}: Read from any node of the cluster.</li><li>{@code ANYREPLICA}: Read from\
    \ any replica node of the cluster.</li><li>{@code NEAREST}: Read from the nearest\
    \ node.</li></ul>"
  shortDescription: "Setting that describes how Lettuce routes read operations to\
    \ replica nodes."
  name: "cas.authn.saml-idp.metadata.redis.read-from"
  defaultValue: ""
- module: "cas-server-support-saml-idp-metadata-redis"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.RedisSamlMetadataProperties"
  type: "java.lang.Integer"
  description: "Connection timeout in milliseconds."
  shortDescription: "Connection timeout in milliseconds."
  name: "cas.authn.saml-idp.metadata.redis.timeout"
  defaultValue: 2000
- module: "cas-server-support-saml-idp-metadata-redis"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.RedisSamlMetadataProperties"
  type: "java.lang.Boolean"
  description: "Whether or not to use SSL for connection factory."
  shortDescription: "Whether or not to use SSL for connection factory."
  name: "cas.authn.saml-idp.metadata.redis.use-ssl"
  defaultValue: false
